### ISSUE TITLE
Content Assist: Invalid location (inside unmodifiable token)

### ISSUE THREAD

**Issue by llucenic** [bruno-medeiros/DDT#100]
Got this after upgrade to latest release 0.11:

![ddt-bug-content-assist](https://cloud.githubusercontent.com/assets/2933634/6665600/9b4b46a4-cbdb-11e4-85f8-58b758983027.png)

I have used intensively previous two versions of DDT and have not encountered this popup. The problem appears at every dot within the q{ } section.

DDT version: 0.11.0
System: Linux Mint 17.1 64bit

Message: Could not perform content assist: Invalid location (inside unmodifiable token)

Eclipse Error Log - Session Data:
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.7.0_75
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=sk_SK
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product

**Comment by bruno-medeiros** [comment]
You can't invoke content assist in the middle of `..` (between the two dots), since that is the range token. This behavior is exactly the same outside of  q{}, and also on DTT version 0.10.4. So perhaps this bug is invalid or not described correctly?
Note that if you are invoking Content Assist and the editor file is not saved, you will stumble across bug #99

**Comment by bruno-medeiros** [comment]
I've found a similar but unrelated bug: #101

**Comment by llucenic** [comment]
Hi Bruno, sorry for not being precise enough in the depiction. The problem appears, when you press the dot while cursor is beyund "node", not from in between the two dots. The screenshot was taken afterwards. Please reopen, as your reason is not the case.

**Comment by bruno-medeiros** [comment]
Hum, I think I see the problem now

**Comment by bruno-medeiros** [comment]
So, is the problem that content assist fails with that error anywhere inside a `q{  }` token string?

**Comment by bruno-medeiros** [comment]
If the issue is that an error dialog appears, instead of the content assist simply not opening, that's #102 
If the issue is that one can't perform content assist inside token strings, I've created #107
If it's something else, explain and I'll reopen

**Comment by llucenic** [comment]
The issue #107 seems to be it for me.
