### ISSUE TITLE
detectLDCInstall uses incorrect paths to find librarySourceFolders

### ISSUE THREAD

**Issue by dmakarov** [bruno-medeiros/DDT#103]
Neither "../include/dlang/ldc" nor "../import/core" are correct locations of D import files in the recent installations of LDC. It should be "../include/d".  (This is in CompilerInstallDetector.java lines 81 -- 97)

**Comment by bruno-medeiros** [comment]
"../import/core" is not a root location of the D import files. For the LDC downloadable archive, it's "../import" and "../import/ldc" (this last one contains object.di).

If you have another layout, I can add it, let me know:
* Which distro is it.
* Which directory includes "object.di", and which directory includes the "std" and "core" dirs, and what's the relative path to the ldc executable, from these directories.

**Comment by dmakarov** [comment]
The ldc is on OS X, installed and built from git source with default configuration settings. The `object.di` is in `/usr/local/include/d/ldc/`, std and core dirs are in `/usr/local/include/d/`. The executable is in `../../../bin` relative to `/usr/local/include/d/std`.

Another distro is the dmd package from Homebrew on Mac OS X. `object.di` is in `/usr/local/include/d2/, std and core dirs are also in `/usr/local/include/d2/` and executable is `/usr/local/bin` or (`../../../bin` relative to `/usr/local/include/d2/std/`.
