### ISSUE TITLE
Unbound buildpath container: 'Default System Library' in project

### ISSUE THREAD

**Issue by aubade** [bruno-medeiros/DDT#104]
The new DDT version seems not to have the DUB dependencies and System library trees present in the Script Explorer anymore, and along with that, every time eclipse starts up I get the error "Unbound buildpath container: 'Default System Library' in project /projectname/"

This, however, doesn't seem to be interfering with code completion of dub dependencies (Which is mostly working, though I'm having the same problems as have already been reported)

**Comment by bruno-medeiros** [comment]
This is actually not a bug. The Script Explorer is deprecated, use the Project Explorer (I'm gradually phasing out DLTK usage). If you want to remove that error, delete the `.buildpath` file, (a simpler one might be recreated).

**Comment by aubade** [comment]
Is there/will there be a replacement for the script explorer's ability to peek inside source files to give a quick code outline? (The outline pane is nice, but as far as I can tell it can only look at one file at a time, and the Project Explorer can't expand files)

**Comment by bruno-medeiros** [comment]
Hum, forgot about that feature, that would be nice to have in Project Explorer too: https://github.com/bruno-medeiros/DDT/issues/106

**Comment by bruno-medeiros** [comment]
Dunno when it will be done though.

**Comment by wanwang2** [comment]
so, I also have this problem.Can you tell me how to solve it? I use shell plugin with eclipse, but the eclipse editor report an error with my shell project.

**Comment by bruno-medeiros** [comment]
> so, I also have this problem.Can you tell me how to solve it? I use shell plugin with eclipse, but the eclipse editor report an error with my shell project.

Please open a new bug report.
