### ISSUE TITLE
0.10.0-PR: Remember folders set as source folders in script explorer

### ISSUE THREAD

**Issue by aubade** [bruno-medeiros/DDT#47]
I use the Script Explorer view quite a bit to quickly reference function and method names and parameters from other files in my project, but in the new version, when I manually set my secondary source folder as containing source so i can expand it, I have to do it every time I start up eclipse. 

I understand this has no effect on the dub build, but it'd be nice all the same :)

**Comment by bruno-medeiros** [comment]
The dependency on DLTK has been removed in the current version, there is no more Script Explorer.
