### ISSUE TITLE
Specifying sub-package leads to JSON error

### ISSUE THREAD

**Issue by gdm85** [bruno-medeiros/DDT#55]
I managed to build a testcase for this problem.

This dub.json will not work:
```
{
    "name": "testMeMore",
    "authors": ["gdm85"],
    "dependencies":
    {
        "dsfml:graphics": "~master",
        "dsfml:audio": "~master"
    }
}
```

this instead will work fine. Notice the different dependencies.
```
{
    "name": "testMeMore",
    "authors": ["gdm85"],
    "dependencies":
    {
        "dsfml": "~master"
    }
}
```

The command that is executed is always 'dub describe', but for some reason the output in the former case throws an error:
```
com.google.gson.stream.MalformedJsonException: Expected name at line 12 column 6
```

**Comment by bruno-medeiros** [comment]
Needs more info, may well be out of date
