### ISSUE TITLE
Tab policy: "Spaces Only" setting not honoured

### ISSUE THREAD

**Issue by luc-j-bourhis** [bruno-medeiros/DDT#91]
With Eclipse Luna SR1 (4.4.1) on MacOS 10.9, I have set up in Preferences > DDT > Editor > Typing
- Tab policy: Spaces only
- Displayed tab size: 2
- Indentation size: 2

but when I hit the Tab key, a tab is inserted instead of 2 spaces. I am sure because I set up Eclipse to display the tab characters everywhere. For the record, I managed to get C++ code to indent with spaces by going to Preferences > C/C++ > Code Style > Formatter and then editing the active profile.

**Comment by bruno-medeiros** [comment]
Correct, it's only being honored when newlines are entered. It should do the same with Tab key, yes.
