### ISSUE TITLE
Attributes on delegates marked as syntax errors

### ISSUE THREAD

**Issue by danielkasza** [bruno-medeiros/DDT#98]
DDT version: 0.10.4.v201412121645
Eclipse version: Luna SR1 (4.4.1)

The following class compiles with dmd:

````
class TestClass {
	this(void delegate() @nogc fn) {
		_fn = fn;
	}
	
	private void delegate() @nogc _fn;
}
````

But produces several error markers in DDT. Removing the `@nogc` attributes fixes the issue, but changes the semantics of the program.

**Comment by bruno-medeiros** [comment]
This was already fixed in 0.11.0
