### ISSUE TITLE
Content Assist: on module throws exception, import problems

### ISSUE THREAD

**Issue by olehlong** [bruno-medeiros/DDT#99]
DDT version - 0.11.0.v201503062245

Hello.
After the recent update from repository I start getting this exception when I'm pressing content assist for module or typing ".". It throws the same exception on class names too. I think, it used to ignore this calls, but not in the new version. 
![selection_020](https://cloud.githubusercontent.com/assets/3706152/6639392/d900516a-c997-11e4-8b09-80a2e384ef03.png)

Also, sometimes it doesn't even show any suggestions for std libraries, only my class, that defined under, or not related to std suggestions. Here an example:

![selection_022](https://cloud.githubusercontent.com/assets/3706152/6639563/66a92996-c999-11e4-9366-107af9482230.png)
![selection_023](https://cloud.githubusercontent.com/assets/3706152/6639564/68d9da3a-c999-11e4-83ab-a94204ffccaa.png)

Sorry for my bad English. Also I don't know how to turn on logging on Eclipse.

**Comment by NCrashed** [comment]
Workaround (I don't know who to fix problems in last release, therefore I downgraded to 10): downgrade to 10 version:

1. Download archive with [previous version](https://github.com/bruno-medeiros/DDT/releases/tag/v0.10.4)

2. Unpack and build with maven terminal command: `mvn package`
P.S. Download [Maven](http://maven.apache.org/) (minimum version 3.0)

3. Make update site `ant -f releng/ CreateProjectSite`

4. Open Eclipse. Uninstall recent version of DDT. Open "Install new software" dialog and add new website, there will be button "Local", point to `/bin-maven/projectSite/releases`. Then follow usual steps of installation guide.

![add repository _052](https://cloud.githubusercontent.com/assets/2116167/6656382/d481c454-cb39-11e4-8796-9ee83d570c5c.png)

![install _053](https://cloud.githubusercontent.com/assets/2116167/6656385/e5c30444-cb39-11e4-9fb1-4bc0affc19b2.png)

**Comment by bruno-medeiros** [comment]
There's an easier way to revert to previous DDT version, if you had it installed before: Go to `Help/Installation Details/Installation History`, look for the entry where you had 0.10.4.v2014... installed and press Revert:
![eclipserevert](https://cloud.githubusercontent.com/assets/4324232/6666220/2bcb784a-cbda-11e4-8e01-6d0da8c2b0b1.png)

In any case I'm looking into this bug now.

**Comment by bruno-medeiros** [comment]
Basically the general form of this bug is: Content Assist is broken if the editor file is not saved.
